/**
 * \addtogroup gbas
 * \{
 * \defgroup Opcodes
 * \addtogroup Opcodes
 * \{
 */

#include "opcodes.h"

const char* keywords[NUM_KEYWORDS] =
{
    "A",
    "B",
    "C",
    "D",
    "E",
    "H",
    "L",
    "AF",
    "BC",
    "DE",
    "HL",
    "SP",

    "Z",
    "NC",
    "NZ",

    "ADC",
    "ADD",
    "AND",
    "BIT",
    "CALL",
    "CCF",
    "CP",
    "CPL",
    "DAA",
    "DEC",
    "DI",
    "EI",
    "HALT",
    "INC",
    "JP",
    "JR",
    "LD",
    "LDD",
    "LDH",
    "LDHL",
    "LDI",
    "NOP",
    "OR",
    "POP",
    "PUSH",
    "RES",
    "RET",
    "RETI",
    "RL",
    "RLA",
    "RLC",
    "RLCA",
    "RR",
    "RRA",
    "RRC",
    "RRCA",
    "RST",
    "SBC",
    "SCF",
    "SET",
    "SLA",
    "SRA",
    "SRL",
    "STOP",
    "SUB",
    "SWAP",
    "XOR"
};

/*========================================================================*//**
 * \brief Candidates opcodes lookup table.
 *
 * - %b means a byte value is required.
 * - %w means a word value is required.
 * - ?xx is a wildcard for any valid numerical representation of the number xx.
 * The number is a part of the mnemonic and no data must be provided.
 *
 * \warning The lexicographical order and spacing allow everything
 * to work.
 *//*=========================================================================*/
const opcode_t opcodes[NUM_OPCODES] =
{
    { "ADC  A  ,     %b     ",    0, 0xCE, 2 },
    { "ADC  A  ,     A      ",    0, 0x8F, 1 },
    { "ADC  A  ,     B      ",    0, 0x88, 1 },
    { "ADC  A  ,     C      ",    0, 0x89, 1 },
    { "ADC  A  ,     D      ",    0, 0x8A, 1 },
    { "ADC  A  ,     E      ",    0, 0x8B, 1 },
    { "ADC  A  ,     H      ",    0, 0x8C, 1 },
    { "ADC  A  ,     L      ",    0, 0x8D, 1 },
    { "ADC  A  ,     [ HL ] ",    0, 0x8E, 1 },

    { "ADD  A  ,     %b     ",    0, 0xC6, 2 },
    { "ADD  A  ,     A      ",    0, 0x87, 1 },
    { "ADD  A  ,     B      ",    0, 0x80, 1 },
    { "ADD  A  ,     C      ",    0, 0x81, 1 },
    { "ADD  A  ,     D      ",    0, 0x82, 1 },
    { "ADD  A  ,     E      ",    0, 0x83, 1 },
    { "ADD  A  ,     H      ",    0, 0x84, 1 },
    { "ADD  A  ,     L      ",    0, 0x85, 1 },
    { "ADD  A  ,     [ HL ] ",    0, 0x86, 1 },

    { "ADD  HL ,     BC     ",    0, 0x09, 1 },
    { "ADD  HL ,     DE     ",    0, 0x19, 1 },
    { "ADD  HL ,     HL     ",    0, 0x29, 1 },
    { "ADD  HL ,     SP     ",    0, 0x39, 1 },
    { "ADD  SP ,     %b     ",    0, 0xE8, 2 },

    { "AND  %b              ",    0, 0xE6, 2 },
    { "AND  A               ",    0, 0xA7, 1 },
    { "AND  B               ",    0, 0xA0, 1 },
    { "AND  C               ",    0, 0xA1, 1 },
    { "AND  D               ",    0, 0xA2, 1 },
    { "AND  E               ",    0, 0xA3, 1 },
    { "AND  H               ",    0, 0xA4, 1 },
    { "AND  L               ",    0, 0xA5, 1 },
    { "AND  [ HL ]          ",    0, 0xA6, 1 },


    { "BIT  ?00  ,   A      ", 0xCB, 0x47, 2 },
    { "BIT  ?00  ,   B      ", 0xCB, 0x40, 2 },
    { "BIT  ?00  ,   C      ", 0xCB, 0x41, 2 },
    { "BIT  ?00  ,   D      ", 0xCB, 0x42, 2 },
    { "BIT  ?00  ,   E      ", 0xCB, 0x43, 2 },
    { "BIT  ?00  ,   H      ", 0xCB, 0x44, 2 },
    { "BIT  ?00  ,   L      ", 0xCB, 0x45, 2 },
    { "BIT  ?00  ,   [ HL ] ", 0xCB, 0x46, 2 },

    { "BIT  ?01  ,   A      ", 0xCB, 0x4F, 2 },
    { "BIT  ?01  ,   B      ", 0xCB, 0x48, 2 },
    { "BIT  ?01  ,   C      ", 0xCB, 0x49, 2 },
    { "BIT  ?01  ,   D      ", 0xCB, 0x4A, 2 },
    { "BIT  ?01  ,   E      ", 0xCB, 0x4B, 2 },
    { "BIT  ?01  ,   H      ", 0xCB, 0x4C, 2 },
    { "BIT  ?01  ,   L      ", 0xCB, 0x4D, 2 },
    { "BIT  ?01  ,   [ HL ] ", 0xCB, 0x4E, 2 },

    { "BIT  ?02  ,   A      ", 0xCB, 0x57, 2 },
    { "BIT  ?02  ,   B      ", 0xCB, 0x50, 2 },
    { "BIT  ?02  ,   C      ", 0xCB, 0x51, 2 },
    { "BIT  ?02  ,   D      ", 0xCB, 0x52, 2 },
    { "BIT  ?02  ,   E      ", 0xCB, 0x53, 2 },
    { "BIT  ?02  ,   H      ", 0xCB, 0x54, 2 },
    { "BIT  ?02  ,   L      ", 0xCB, 0x55, 2 },
    { "BIT  ?02  ,   [ HL ] ", 0xCB, 0x56, 2 },

    { "BIT  ?03  ,   A      ", 0xCB, 0x5F, 2 },
    { "BIT  ?03  ,   B      ", 0xCB, 0x58, 2 },
    { "BIT  ?03  ,   C      ", 0xCB, 0x59, 2 },
    { "BIT  ?03  ,   D      ", 0xCB, 0x5A, 2 },
    { "BIT  ?03  ,   E      ", 0xCB, 0x5B, 2 },
    { "BIT  ?03  ,   H      ", 0xCB, 0x5C, 2 },
    { "BIT  ?03  ,   L      ", 0xCB, 0x5D, 2 },
    { "BIT  ?03  ,   [ HL ] ", 0xCB, 0x5E, 2 },

    { "BIT  ?04  ,   A      ", 0xCB, 0x67, 2 },
    { "BIT  ?04  ,   B      ", 0xCB, 0x60, 2 },
    { "BIT  ?04  ,   C      ", 0xCB, 0x61, 2 },
    { "BIT  ?04  ,   D      ", 0xCB, 0x62, 2 },
    { "BIT  ?04  ,   E      ", 0xCB, 0x63, 2 },
    { "BIT  ?04  ,   H      ", 0xCB, 0x64, 2 },
    { "BIT  ?04  ,   L      ", 0xCB, 0x65, 2 },
    { "BIT  ?04  ,   [ HL ] ", 0xCB, 0x66, 2 },

    { "BIT  ?05  ,   A      ", 0xCB, 0x6F, 2 },
    { "BIT  ?05  ,   B      ", 0xCB, 0x68, 2 },
    { "BIT  ?05  ,   C      ", 0xCB, 0x69, 2 },
    { "BIT  ?05  ,   D      ", 0xCB, 0x6A, 2 },
    { "BIT  ?05  ,   E      ", 0xCB, 0x6B, 2 },
    { "BIT  ?05  ,   H      ", 0xCB, 0x6C, 2 },
    { "BIT  ?05  ,   L      ", 0xCB, 0x6D, 2 },
    { "BIT  ?05  ,   [ HL ] ", 0xCB, 0x6E, 2 },

    { "BIT  ?06  ,   A      ", 0xCB, 0x77, 2 },
    { "BIT  ?06  ,   B      ", 0xCB, 0x70, 2 },
    { "BIT  ?06  ,   C      ", 0xCB, 0x71, 2 },
    { "BIT  ?06  ,   D      ", 0xCB, 0x72, 2 },
    { "BIT  ?06  ,   E      ", 0xCB, 0x73, 2 },
    { "BIT  ?06  ,   H      ", 0xCB, 0x74, 2 },
    { "BIT  ?06  ,   L      ", 0xCB, 0x75, 2 },
    { "BIT  ?06  ,   [ HL ] ", 0xCB, 0x76, 2 },

    { "BIT  ?07  ,   A      ", 0xCB, 0x7F, 2 },
    { "BIT  ?07  ,   B      ", 0xCB, 0x78, 2 },
    { "BIT  ?07  ,   C      ", 0xCB, 0x79, 2 },
    { "BIT  ?07  ,   D      ", 0xCB, 0x7A, 2 },
    { "BIT  ?07  ,   E      ", 0xCB, 0x7B, 2 },
    { "BIT  ?07  ,   H      ", 0xCB, 0x7C, 2 },
    { "BIT  ?07  ,   L      ", 0xCB, 0x7D, 2 },
    { "BIT  ?07  ,   [ HL ] ", 0xCB, 0x7E, 2 },

    { "CALL %w              ",    0, 0xCD, 3 },
    { "CALL C  ,     %w     ",    0, 0xDC, 3 },
    { "CALL NC ,     %w     ",    0, 0xD4, 3 },
    { "CALL NZ ,     %w     ",    0, 0xC4, 3 },
    { "CALL Z  ,     %w     ",    0, 0xCC, 3 },

    { "CCF                  ",    0, 0x3F, 1 },

    { "CP   %b              ",    0, 0xFE, 2 },
    { "CP   A               ",    0, 0xBF, 1 },
    { "CP   B               ",    0, 0xB8, 1 },
    { "CP   C               ",    0, 0xB9, 1 },
    { "CP   D               ",    0, 0xBA, 1 },
    { "CP   E               ",    0, 0xBB, 1 },
    { "CP   H               ",    0, 0xBC, 1 },
    { "CP   L               ",    0, 0xBD, 1 },
    { "CP   [ HL ]          ",    0, 0xBE, 1 },

    { "CPL                  ",    0, 0x2F, 1 },

    { "DAA                  ",    0, 0x27, 1 },

    { "DEC  A               ",    0, 0x3D, 1 },
    { "DEC  B               ",    0, 0x05, 1 },
    { "DEC  BC              ",    0, 0x0B, 1 },
    { "DEC  C               ",    0, 0x0D, 1 },
    { "DEC  D               ",    0, 0x15, 1 },
    { "DEC  DE              ",    0, 0x1B, 1 },
    { "DEC  E               ",    0, 0x1D, 1 },
    { "DEC  H               ",    0, 0x25, 1 },
    { "DEC  HL              ",    0, 0x2B, 1 },
    { "DEC  L               ",    0, 0x2D, 1 },
    { "DEC  SP              ",    0, 0x3B, 1 },
    { "DEC  [ HL ]          ",    0, 0x35, 1 },

    { "DI                   ",    0, 0xF3, 1 },

    { "EI                   ",    0, 0xFB, 1 },

    { "HALT                 ",    0, 0x76, 1 },

    { "INC  A               ",    0, 0x3C, 1 },
    { "INC  B               ",    0, 0x04, 1 },
    { "INC  BC              ",    0, 0x03, 1 },
    { "INC  C               ",    0, 0x0C, 1 },
    { "INC  D               ",    0, 0x14, 1 },
    { "INC  DE              ",    0, 0x13, 1 },
    { "INC  E               ",    0, 0x1C, 1 },
    { "INC  H               ",    0, 0x24, 1 },
    { "INC  HL              ",    0, 0x23, 1 },
    { "INC  L               ",    0, 0x2C, 1 },
    { "INC  SP              ",    0, 0x33, 1 },
    { "INC  [ HL ]          ",    0, 0x34, 1 },

    { "JP   %w              ",    0, 0xC3, 3 },
    { "JP   C  ,     %w     ",    0, 0xDA, 3 },
    { "JP   NC ,     %w     ",    0, 0xD2, 3 },
    { "JP   NZ ,     %w     ",    0, 0xC2, 3 },
    { "JP   Z  ,     %w     ",    0, 0xCA, 3 },
    { "JP   [ HL ]          ",    0, 0xE9, 1 },

    { "JR   %b              ",    0, 0x18, 2 },
    { "JR   C  ,     %b     ",    0, 0x38, 2 },
    { "JR   NC ,     %b     ",    0, 0x30, 2 },
    { "JR   NZ ,     %b     ",    0, 0x20, 2 },
    { "JR   Z  ,     %b     ",    0, 0x28, 2 },

    { "LD   A ,      %b     ",    0, 0x3E, 2 },
    { "LD   A ,      A      ",    0, 0x7F, 1 },
    { "LD   A ,      B      ",    0, 0x78, 1 },
    { "LD   A ,      C      ",    0, 0x79, 1 },
    { "LD   A ,      D      ",    0, 0x7A, 1 },
    { "LD   A ,      E      ",    0, 0x7B, 1 },
    { "LD   A ,      H      ",    0, 0x7C, 1 },
    { "LD   A ,      L      ",    0, 0x7D, 1 },
    { "LD   A ,      [ %w ] ",    0, 0xFA, 3 },
    { "LD   A ,      [ BC ] ",    0, 0x0A, 1 },
    { "LD   A ,      [ C ]  ",    0, 0xF2, 1 },
    { "LD   A ,      [ DE ] ",    0, 0x1A, 1 },
    { "LD   A ,      [ HL ] ",    0, 0x7E, 1 },


    { "LD   B ,      %b     ",    0, 0x06, 2 },
    { "LD   B ,      A      ",    0, 0x47, 1 },
    { "LD   B ,      B      ",    0, 0x40, 1 },
    { "LD   B ,      C      ",    0, 0x41, 1 },
    { "LD   B ,      D      ",    0, 0x42, 1 },
    { "LD   B ,      E      ",    0, 0x43, 1 },
    { "LD   B ,      H      ",    0, 0x44, 1 },
    { "LD   B ,      L      ",    0, 0x45, 1 },
    { "LD   B ,      [ HL ] ",    0, 0x46, 1 },

    { "LD   BC ,     %w     ",    0, 0x01, 3 },

    { "LD   C ,      %b     ",    0, 0x0E, 2 },
    { "LD   C ,      A      ",    0, 0x4F, 1 },
    { "LD   C ,      B      ",    0, 0x48, 1 },
    { "LD   C ,      C      ",    0, 0x49, 1 },
    { "LD   C ,      D      ",    0, 0x4A, 1 },
    { "LD   C ,      E      ",    0, 0x4B, 1 },
    { "LD   C ,      H      ",    0, 0x4C, 1 },
    { "LD   C ,      L      ",    0, 0x4D, 1 },
    { "LD   C ,      [ HL ] ",    0, 0x4E, 1 },

    { "LD   D ,      %b     ",    0, 0x16, 2 },
    { "LD   D ,      A      ",    0, 0x57, 1 },
    { "LD   D ,      B      ",    0, 0x50, 1 },
    { "LD   D ,      C      ",    0, 0x51, 1 },
    { "LD   D ,      D      ",    0, 0x52, 1 },
    { "LD   D ,      E      ",    0, 0x53, 1 },
    { "LD   D ,      H      ",    0, 0x54, 1 },
    { "LD   D ,      L      ",    0, 0x55, 1 },
    { "LD   D ,      [ HL ] ",    0, 0x56, 1 },

    { "LD   DE ,     %w     ",    0, 0x11, 3 },

    { "LD   E ,      %b     ",    0, 0x1E, 2 },
    { "LD   E ,      A      ",    0, 0x5F, 1 },
    { "LD   E ,      B      ",    0, 0x58, 1 },
    { "LD   E ,      C      ",    0, 0x59, 1 },
    { "LD   E ,      D      ",    0, 0x5A, 1 },
    { "LD   E ,      E      ",    0, 0x5B, 1 },
    { "LD   E ,      H      ",    0, 0x5C, 1 },
    { "LD   E ,      L      ",    0, 0x5D, 1 },
    { "LD   E ,      [ HL ] ",    0, 0x5E, 1 },

    { "LD   H ,      %b     ",    0, 0x26, 2 },
    { "LD   H ,      A      ",    0, 0x67, 1 },
    { "LD   H ,      B      ",    0, 0x60, 1 },
    { "LD   H ,      C      ",    0, 0x61, 1 },
    { "LD   H ,      D      ",    0, 0x62, 1 },
    { "LD   H ,      E      ",    0, 0x63, 1 },
    { "LD   H ,      H      ",    0, 0x64, 1 },
    { "LD   H ,      L      ",    0, 0x65, 1 },
    { "LD   H ,      [ HL ] ",    0, 0x66, 1 },

    { "LD   HL ,     %w     ",    0, 0x21, 3 },

    { "LD   L ,      %b     ",    0, 0x2E, 2 },
    { "LD   L ,      A      ",    0, 0x6F, 1 },
    { "LD   L ,      B      ",    0, 0x68, 1 },
    { "LD   L ,      C      ",    0, 0x69, 1 },
    { "LD   L ,      D      ",    0, 0x6A, 1 },
    { "LD   L ,      E      ",    0, 0x6B, 1 },
    { "LD   L ,      H      ",    0, 0x6C, 1 },
    { "LD   L ,      L      ",    0, 0x6D, 1 },
    { "LD   L ,      [ HL ] ",    0, 0x6E, 1 },

    { "LD   SP ,     %w     ",    0, 0x31, 3 },
    { "LD   SP ,     HL     ",    0, 0xF9, 1 },

    { "LD   [ %w ] , A      ",    0, 0xEA, 3 },
    { "LD   [ %w ] , SP     ",    0, 0x08, 3 },

    { "LD   [ BC ] , A      ",    0, 0x02, 1 },
    { "LD   [ C ]  , A      ",    0, 0xE2, 1 },
    { "LD   [ DE ] , A      ",    0, 0x12, 1 },
    { "LD   [ HL ] , %b     ",    0, 0x36, 2 },
    { "LD   [ HL ] , A      ",    0, 0x77, 1 },
    { "LD   [ HL ] , B      ",    0, 0x70, 1 },
    { "LD   [ HL ] , C      ",    0, 0x71, 1 },
    { "LD   [ HL ] , D      ",    0, 0x72, 1 },
    { "LD   [ HL ] , E      ",    0, 0x73, 1 },
    { "LD   [ HL ] , H      ",    0, 0x74, 1 },
    { "LD   [ HL ] , L      ",    0, 0x75, 1 },

    { "LDD  A      , [ HL ] ",    0, 0x3A, 1 },
    { "LDD  [ HL ] , A      ",    0, 0x32, 1 },

    { "LDH  A      , [ %b ] ",    0, 0xF0, 2 },
    { "LDH  [ %b ] , A      ",    0, 0xE0, 2 },

    { "LDHL SP ,     %b     ",    0, 0xF8, 2 },

    { "LDI  A      , [ HL ] ",    0, 0x2A, 1 },
    { "LDI  [ HL ] , A      ",    0, 0x22, 1 },

    { "NOP                  ",    0, 0x00, 1 },

    { "OR   %b              ",    0, 0xF6, 2 },
    { "OR   A               ",    0, 0xB7, 1 },
    { "OR   B               ",    0, 0xB0, 1 },
    { "OR   C               ",    0, 0xB1, 1 },
    { "OR   D               ",    0, 0xB2, 1 },
    { "OR   E               ",    0, 0xB3, 1 },
    { "OR   H               ",    0, 0xB4, 1 },
    { "OR   L               ",    0, 0xB5, 1 },
    { "OR   [ HL ]          ",    0, 0xB6, 1 },


    { "POP  AF              ",    0, 0xF1, 1 },
    { "POP  BC              ",    0, 0xC1, 1 },
    { "POP  DE              ",    0, 0xD1, 1 },
    { "POP  HL              ",    0, 0xE1, 1 },

    { "PUSH AF              ",    0, 0xF5, 1 },
    { "PUSH BC              ",    0, 0xC5, 1 },
    { "PUSH DE              ",    0, 0xD5, 1 },
    { "PUSH HL              ",    0, 0xE5, 1 },

    { "RES  ?00  ,   A      ", 0xCB, 0x87, 2 },
    { "RES  ?00  ,   B      ", 0xCB, 0x80, 2 },
    { "RES  ?00  ,   C      ", 0xCB, 0x81, 2 },
    { "RES  ?00  ,   D      ", 0xCB, 0x82, 2 },
    { "RES  ?00  ,   E      ", 0xCB, 0x83, 2 },
    { "RES  ?00  ,   H      ", 0xCB, 0x84, 2 },
    { "RES  ?00  ,   L      ", 0xCB, 0x85, 2 },
    { "RES  ?00  ,   [ HL ] ", 0xCB, 0x86, 2 },

    { "RES  ?01  ,   A      ", 0xCB, 0x8F, 2 },
    { "RES  ?01  ,   B      ", 0xCB, 0x88, 2 },
    { "RES  ?01  ,   C      ", 0xCB, 0x89, 2 },
    { "RES  ?01  ,   D      ", 0xCB, 0x8A, 2 },
    { "RES  ?01  ,   E      ", 0xCB, 0x8B, 2 },
    { "RES  ?01  ,   H      ", 0xCB, 0x8C, 2 },
    { "RES  ?01  ,   L      ", 0xCB, 0x8D, 2 },
    { "RES  ?01  ,   [ HL ] ", 0xCB, 0x8E, 2 },

    { "RES  ?02  ,   A      ", 0xCB, 0x97, 2 },
    { "RES  ?02  ,   B      ", 0xCB, 0x90, 2 },
    { "RES  ?02  ,   C      ", 0xCB, 0x91, 2 },
    { "RES  ?02  ,   D      ", 0xCB, 0x92, 2 },
    { "RES  ?02  ,   E      ", 0xCB, 0x93, 2 },
    { "RES  ?02  ,   H      ", 0xCB, 0x94, 2 },
    { "RES  ?02  ,   L      ", 0xCB, 0x95, 2 },
    { "RES  ?02  ,   [ HL ] ", 0xCB, 0x96, 2 },

    { "RES  ?03  ,   A      ", 0xCB, 0x9F, 2 },
    { "RES  ?03  ,   B      ", 0xCB, 0x98, 2 },
    { "RES  ?03  ,   C      ", 0xCB, 0x99, 2 },
    { "RES  ?03  ,   D      ", 0xCB, 0x9A, 2 },
    { "RES  ?03  ,   E      ", 0xCB, 0x9B, 2 },
    { "RES  ?03  ,   H      ", 0xCB, 0x9C, 2 },
    { "RES  ?03  ,   L      ", 0xCB, 0x9D, 2 },
    { "RES  ?03  ,   [ HL ] ", 0xCB, 0x9E, 2 },

    { "RES  ?04  ,   A      ", 0xCB, 0xA7, 2 },
    { "RES  ?04  ,   B      ", 0xCB, 0xA0, 2 },
    { "RES  ?04  ,   C      ", 0xCB, 0xA1, 2 },
    { "RES  ?04  ,   D      ", 0xCB, 0xA2, 2 },
    { "RES  ?04  ,   E      ", 0xCB, 0xA3, 2 },
    { "RES  ?04  ,   H      ", 0xCB, 0xA4, 2 },
    { "RES  ?04  ,   L      ", 0xCB, 0xA5, 2 },
    { "RES  ?04  ,   [ HL ] ", 0xCB, 0xA6, 2 },

    { "RES  ?05  ,   A      ", 0xCB, 0xAF, 2 },
    { "RES  ?05  ,   B      ", 0xCB, 0xA8, 2 },
    { "RES  ?05  ,   C      ", 0xCB, 0xA9, 2 },
    { "RES  ?05  ,   D      ", 0xCB, 0xAA, 2 },
    { "RES  ?05  ,   E      ", 0xCB, 0xAB, 2 },
    { "RES  ?05  ,   H      ", 0xCB, 0xAC, 2 },
    { "RES  ?05  ,   L      ", 0xCB, 0xAD, 2 },
    { "RES  ?05  ,   [ HL ] ", 0xCB, 0xAE, 2 },

    { "RES  ?06  ,   A      ", 0xCB, 0xB7, 2 },
    { "RES  ?06  ,   B      ", 0xCB, 0xB0, 2 },
    { "RES  ?06  ,   C      ", 0xCB, 0xB1, 2 },
    { "RES  ?06  ,   D      ", 0xCB, 0xB2, 2 },
    { "RES  ?06  ,   E      ", 0xCB, 0xB3, 2 },
    { "RES  ?06  ,   H      ", 0xCB, 0xB4, 2 },
    { "RES  ?06  ,   L      ", 0xCB, 0xB5, 2 },
    { "RES  ?06  ,   [ HL ] ", 0xCB, 0xB6, 2 },

    { "RES  ?07  ,   A      ", 0xCB, 0xBF, 2 },
    { "RES  ?07  ,   B      ", 0xCB, 0xB8, 2 },
    { "RES  ?07  ,   C      ", 0xCB, 0xB9, 2 },
    { "RES  ?07  ,   D      ", 0xCB, 0xBA, 2 },
    { "RES  ?07  ,   E      ", 0xCB, 0xBB, 2 },
    { "RES  ?07  ,   H      ", 0xCB, 0xBC, 2 },
    { "RES  ?07  ,   L      ", 0xCB, 0xBD, 2 },
    { "RES  ?07  ,   [ HL ] ", 0xCB, 0xBE, 2 },

    { "RET                  ",    0, 0xC9, 1 },
    { "RET  C               ",    0, 0xD8, 1 },
    { "RET  NC              ",    0, 0xD0, 1 },
    { "RET  NZ              ",    0, 0xC0, 1 },
    { "RET  Z               ",    0, 0xC8, 1 },

    { "RETI                 ",    0, 0xD9, 1 },

    { "RL   A               ", 0xCB, 0x17, 2 },
    { "RL   B               ", 0xCB, 0x10, 2 },
    { "RL   C               ", 0xCB, 0x11, 2 },
    { "RL   D               ", 0xCB, 0x12, 2 },
    { "RL   E               ", 0xCB, 0x13, 2 },
    { "RL   H               ", 0xCB, 0x14, 2 },
    { "RL   L               ", 0xCB, 0x15, 2 },
    { "RL   [ HL ]          ", 0xCB, 0x16, 2 },

    { "RLA                  ",    0, 0x17, 1 },

    { "RLC  A               ", 0xCB, 0x07, 2 },
    { "RLC  B               ", 0xCB, 0x00, 2 },
    { "RLC  C               ", 0xCB, 0x01, 2 },
    { "RLC  D               ", 0xCB, 0x02, 2 },
    { "RLC  E               ", 0xCB, 0x03, 2 },
    { "RLC  H               ", 0xCB, 0x04, 2 },
    { "RLC  L               ", 0xCB, 0x05, 2 },
    { "RLC  [ HL ]          ", 0xCB, 0x06, 2 },

    { "RLCA                 ",    0, 0x07, 1 },

    { "RR   A               ", 0xCB, 0x1F, 2 },
    { "RR   B               ", 0xCB, 0x18, 2 },
    { "RR   C               ", 0xCB, 0x19, 2 },
    { "RR   D               ", 0xCB, 0x1A, 2 },
    { "RR   E               ", 0xCB, 0x1B, 2 },
    { "RR   H               ", 0xCB, 0x1C, 2 },
    { "RR   L               ", 0xCB, 0x1D, 2 },
    { "RR   [ HL ]          ", 0xCB, 0x1E, 2 },

    { "RRA                  ",    0, 0x1F, 1 },

    { "RRC  A               ", 0xCB, 0x0F, 2 },
    { "RRC  B               ", 0xCB, 0x08, 2 },
    { "RRC  C               ", 0xCB, 0x09, 2 },
    { "RRC  D               ", 0xCB, 0x0A, 2 },
    { "RRC  E               ", 0xCB, 0x0B, 2 },
    { "RRC  H               ", 0xCB, 0x0C, 2 },
    { "RRC  L               ", 0xCB, 0x0D, 2 },
    { "RRC  [ HL ]          ", 0xCB, 0x0E, 2 },

    { "RRCA                 ",    0, 0x0F, 1 },

    { "RST  ?00             ",    0, 0xC7, 1 },
    { "RST  ?08             ",    0, 0xCF, 1 },
    { "RST  ?10             ",    0, 0xD7, 1 },
    { "RST  ?18             ",    0, 0xDF, 1 },
    { "RST  ?20             ",    0, 0xE7, 1 },
    { "RST  ?28             ",    0, 0xEF, 1 },
    { "RST  ?30             ",    0, 0xF7, 1 },
    { "RST  ?38             ",    0, 0xFF, 1 },

    { "SBC  A  ,     %b     ",    0, 0xDE, 2 },
    { "SBC  A  ,     A      ",    0, 0x9F, 1 },
    { "SBC  A  ,     B      ",    0, 0x98, 1 },
    { "SBC  A  ,     C      ",    0, 0x99, 1 },
    { "SBC  A  ,     D      ",    0, 0x9A, 1 },
    { "SBC  A  ,     E      ",    0, 0x9B, 1 },
    { "SBC  A  ,     H      ",    0, 0x9C, 1 },
    { "SBC  A  ,     L      ",    0, 0x9D, 1 },
    { "SBC  A  ,     [ HL ] ",    0, 0x9E, 1 },

    { "SCF                  ",    0, 0x37, 1 },

    { "SET  ?00  ,   A      ", 0xCB, 0xC7, 2 },
    { "SET  ?00  ,   B      ", 0xCB, 0xC0, 2 },
    { "SET  ?00  ,   C      ", 0xCB, 0xC1, 2 },
    { "SET  ?00  ,   D      ", 0xCB, 0xC2, 2 },
    { "SET  ?00  ,   E      ", 0xCB, 0xC3, 2 },
    { "SET  ?00  ,   H      ", 0xCB, 0xC4, 2 },
    { "SET  ?00  ,   L      ", 0xCB, 0xC5, 2 },
    { "SET  ?00  ,   [ HL ] ", 0xCB, 0xC6, 2 },

    { "SET  ?01  ,   A      ", 0xCB, 0xCF, 2 },
    { "SET  ?01  ,   B      ", 0xCB, 0xC8, 2 },
    { "SET  ?01  ,   C      ", 0xCB, 0xC9, 2 },
    { "SET  ?01  ,   D      ", 0xCB, 0xCA, 2 },
    { "SET  ?01  ,   E      ", 0xCB, 0xCB, 2 },
    { "SET  ?01  ,   H      ", 0xCB, 0xCC, 2 },
    { "SET  ?01  ,   L      ", 0xCB, 0xCD, 2 },
    { "SET  ?01  ,   [ HL ] ", 0xCB, 0xCE, 2 },

    { "SET  ?02  ,   A      ", 0xCB, 0xD7, 2 },
    { "SET  ?02  ,   B      ", 0xCB, 0xD0, 2 },
    { "SET  ?02  ,   C      ", 0xCB, 0xD1, 2 },
    { "SET  ?02  ,   D      ", 0xCB, 0xD2, 2 },
    { "SET  ?02  ,   E      ", 0xCB, 0xD3, 2 },
    { "SET  ?02  ,   H      ", 0xCB, 0xD4, 2 },
    { "SET  ?02  ,   L      ", 0xCB, 0xD5, 2 },
    { "SET  ?02  ,   [ HL ] ", 0xCB, 0xD6, 2 },

    { "SET  ?03  ,   A      ", 0xCB, 0xDF, 2 },
    { "SET  ?03  ,   B      ", 0xCB, 0xD8, 2 },
    { "SET  ?03  ,   C      ", 0xCB, 0xD9, 2 },
    { "SET  ?03  ,   D      ", 0xCB, 0xDA, 2 },
    { "SET  ?03  ,   E      ", 0xCB, 0xDB, 2 },
    { "SET  ?03  ,   H      ", 0xCB, 0xDC, 2 },
    { "SET  ?03  ,   L      ", 0xCB, 0xDD, 2 },
    { "SET  ?03  ,   [ HL ] ", 0xCB, 0xDE, 2 },

    { "SET  ?04  ,   A      ", 0xCB, 0xE7, 2 },
    { "SET  ?04  ,   B      ", 0xCB, 0xE0, 2 },
    { "SET  ?04  ,   C      ", 0xCB, 0xE1, 2 },
    { "SET  ?04  ,   D      ", 0xCB, 0xE2, 2 },
    { "SET  ?04  ,   E      ", 0xCB, 0xE3, 2 },
    { "SET  ?04  ,   H      ", 0xCB, 0xE4, 2 },
    { "SET  ?04  ,   L      ", 0xCB, 0xE5, 2 },
    { "SET  ?04  ,   [ HL ] ", 0xCB, 0xE6, 2 },

    { "SET  ?05  ,   A      ", 0xCB, 0xEF, 2 },
    { "SET  ?05  ,   B      ", 0xCB, 0xE8, 2 },
    { "SET  ?05  ,   C      ", 0xCB, 0xE9, 2 },
    { "SET  ?05  ,   D      ", 0xCB, 0xEA, 2 },
    { "SET  ?05  ,   E      ", 0xCB, 0xEB, 2 },
    { "SET  ?05  ,   H      ", 0xCB, 0xEC, 2 },
    { "SET  ?05  ,   L      ", 0xCB, 0xED, 2 },
    { "SET  ?05  ,   [ HL ] ", 0xCB, 0xEE, 2 },

    { "SET  ?06  ,   A      ", 0xCB, 0xF7, 2 },
    { "SET  ?06  ,   B      ", 0xCB, 0xF0, 2 },
    { "SET  ?06  ,   C      ", 0xCB, 0xF1, 2 },
    { "SET  ?06  ,   D      ", 0xCB, 0xF2, 2 },
    { "SET  ?06  ,   E      ", 0xCB, 0xF3, 2 },
    { "SET  ?06  ,   H      ", 0xCB, 0xF4, 2 },
    { "SET  ?06  ,   L      ", 0xCB, 0xF5, 2 },
    { "SET  ?06  ,   [ HL ] ", 0xCB, 0xF6, 2 },

    { "SET  ?07  ,   A      ", 0xCB, 0xFF, 2 },
    { "SET  ?07  ,   B      ", 0xCB, 0xF8, 2 },
    { "SET  ?07  ,   C      ", 0xCB, 0xF9, 2 },
    { "SET  ?07  ,   D      ", 0xCB, 0xFA, 2 },
    { "SET  ?07  ,   E      ", 0xCB, 0xFB, 2 },
    { "SET  ?07  ,   H      ", 0xCB, 0xFC, 2 },
    { "SET  ?07  ,   L      ", 0xCB, 0xFD, 2 },
    { "SET  ?07  ,   [ HL ] ", 0xCB, 0xFE, 2 },

    { "SLA  A               ", 0xCB, 0x27, 2 },
    { "SLA  B               ", 0xCB, 0x20, 2 },
    { "SLA  C               ", 0xCB, 0x21, 2 },
    { "SLA  D               ", 0xCB, 0x22, 2 },
    { "SLA  E               ", 0xCB, 0x23, 2 },
    { "SLA  H               ", 0xCB, 0x24, 2 },
    { "SLA  L               ", 0xCB, 0x25, 2 },
    { "SLA  [ HL ]          ", 0xCB, 0x26, 2 },

    { "SRA  A               ", 0xCB, 0x2F, 2 },
    { "SRA  B               ", 0xCB, 0x28, 2 },
    { "SRA  C               ", 0xCB, 0x29, 2 },
    { "SRA  D               ", 0xCB, 0x2A, 2 },
    { "SRA  E               ", 0xCB, 0x2B, 2 },
    { "SRA  H               ", 0xCB, 0x2C, 2 },
    { "SRA  L               ", 0xCB, 0x2D, 2 },
    { "SRA  [ HL ]          ", 0xCB, 0x2E, 2 },

    { "SRL  A               ", 0xCB, 0x3F, 2 },
    { "SRL  B               ", 0xCB, 0x38, 2 },
    { "SRL  C               ", 0xCB, 0x39, 2 },
    { "SRL  D               ", 0xCB, 0x3A, 2 },
    { "SRL  E               ", 0xCB, 0x3B, 2 },
    { "SRL  H               ", 0xCB, 0x3C, 2 },
    { "SRL  L               ", 0xCB, 0x3D, 2 },
    { "SRL  [ HL ]          ", 0xCB, 0x3E, 2 },

    { "STOP                 ",    0, 0x10, 1 },

    { "SUB  %b              ",    0, 0xD6, 2 },
    { "SUB  A               ",    0, 0x97, 1 },
    { "SUB  B               ",    0, 0x90, 1 },
    { "SUB  C               ",    0, 0x91, 1 },
    { "SUB  D               ",    0, 0x92, 1 },
    { "SUB  E               ",    0, 0x93, 1 },
    { "SUB  H               ",    0, 0x94, 1 },
    { "SUB  L               ",    0, 0x95, 1 },
    { "SUB  [ HL ]          ",    0, 0x96, 1 },

    { "SWAP A               ", 0xCB, 0x37, 2 },
    { "SWAP B               ", 0xCB, 0x30, 2 },
    { "SWAP C               ", 0xCB, 0x31, 2 },
    { "SWAP D               ", 0xCB, 0x32, 2 },
    { "SWAP E               ", 0xCB, 0x33, 2 },
    { "SWAP H               ", 0xCB, 0x34, 2 },
    { "SWAP L               ", 0xCB, 0x35, 2 },
    { "SWAP [ HL ]          ", 0xCB, 0x36, 2 },

    { "XOR  %b              ",    0, 0xEE, 2 },
    { "XOR  A               ",    0, 0xAF, 1 },
    { "XOR  B               ",    0, 0xA8, 1 },
    { "XOR  C               ",    0, 0xA9, 1 },
    { "XOR  D               ",    0, 0xAA, 1 },
    { "XOR  E               ",    0, 0xAB, 1 },
    { "XOR  H               ",    0, 0xAC, 1 },
    { "XOR  L               ",    0, 0xAD, 1 },
    { "XOR  [ HL ]          ",    0, 0xAE, 1 }
};

/**
 * \} Opcodes
 * \} gbas
 */

