/*========================================================================*//**
 * \addtogroup Commons
 * \{
 * \defgroup Errors
 * \addtogroup Errors
 * \{
 *//*=========================================================================*/

#include "errors.h"

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdarg.h>

#include "utils.h"

#ifdef _WIN32
const char* const notestr = "note";
const char* const warnstr = "warning";
const char* const errstr  = "error";
const char* const ferrstr = "fatal error";
#else
const char* const notestr = "\x1B[36mnote\x1B[0m: ";
const char* const warnstr = "\x1B[33mwarning\x1B[0m: ";
const char* const errstr  = "\x1B[31merror\x1B[0m: ";
const char* const ferrstr = "\x1B[35mfatal error\x1B[0m: ";
#endif

int eline;   /**< Line to display in error messages */
int ecolumn; /**< Column to display in error messages */
static const char* program; /**< Program name to display on error messages */
static void (*onfatal)() = NULL; /**< Function to call in case of a fatal err */
static char* efile = NULL;      /**< File name to display in error messages */
static int error_count = 0;     /**< Total number of errors */
static int warning_count = 0;   /**< Total number of warnings */
static int is_fatal = 0;        /**< Non-zero means the last error was fatal */
static int last_line = -1;      /**< Last error line */
static int last_col = -1;       /**< Last error column */
static int last_lvl = W;        /**< Last error level/type */

static void verr(errtype_t type, const char* message, va_list args, int prgm);

/*========================================================================*//**
 * Set the program name to display in further error messages
 *
 * \param name: the name to display
 *//*=========================================================================*/
void esetprogram(const char* const name)
{
    program = name;
}

/*========================================================================*//**
 * Set the function to call in case of fatal error
 *
 * \param func: The function to call
 *//*=========================================================================*/
void esetonfatal(void(*func)())
{
    onfatal = func;
}

/*========================================================================*//**
 * Set the file name to display in further error messages
 *
 * \param name: The file name to display
 *//*=========================================================================*/
void esetfile(const char* name)
{
    efile = (char*)mrealloc(efile, strlen(name) + 1);
    strcpy(efile, name);
    last_line = -1;
    last_col = -1;
    last_lvl = W;
}

/*========================================================================*//**
 * Return the number of errors
 *//*=========================================================================*/
int errors()
{
    return error_count;
}

/*========================================================================*//**
 * Return the number of warnings
 *//*=========================================================================*/
int warnings()
{
    return warning_count;
}

/*========================================================================*//**
 * Return true if the last error is fatal
 *//*=========================================================================*/
int fatal()
{
    return is_fatal;
}

void add_error()
{
    ++error_count;
}

/*========================================================================*//**
 * Reset the number of errors
 *//*=========================================================================*/
void clear_errors()
{
    error_count = 0;
    warning_count = 0;
}

/*========================================================================*//**
 * Reset the 'fatal' flag
 *//*=========================================================================*/
void clear_fatal()
{
    is_fatal = 0;
}

/*========================================================================*//**
 * Display a formatted error message for an error generated by a flaw in a
 * source file. If the error is a fatal error, call the function registered with
 * esetonfatal().
 *
 * \param type: the error type
 * \param message: the string to display. Format specifiers are those
 * of printf()
 * \param ...: additional arguments depending on the format string
 *//*=========================================================================*/
void err(errtype_t type, const char* message, ...)
{
    va_list args;
#ifdef NDEBUG
    /* The recursive parser can generate a new error at each recursion level */
    if (eline == last_line && ecolumn == last_col && (int)type <= last_lvl)
        return;
#endif


    if (eline > 0 && ecolumn > 0)
        fprintf(stderr, "%s:%d:%d: ", efile, eline, ecolumn);
    else
        fprintf(stderr, "%s: ", efile);
    va_start(args, message);
    verr(type, message, args, 0);
    va_end(args);
}

/*========================================================================*//**
 * Display a formatted error message for an error generated by the program.
 * If the error is a fatal error, call the function registered with
 * esetonfatal().
 *
 * \param type: the error type
 * \param message: the string to display. Format specifiers are those
 * of printf()
 * \param ...: additional arguments depending on the format string
 *//*=========================================================================*/
void ccerr(errtype_t type, const char* message, ...)
{
    va_list args;
    /* if (eline == last_line && ecolumn == last_col && (int)type <= last_lvl)
        return; */

    fprintf(stderr, "%s: ", program);
    va_start(args, message);
    verr(type, message, args, 1);
    va_end(args);
}

/*========================================================================*//**
 * Display a formatted error message. If the error is a fatal error, call the
 * function registered with esetonfatal().
 *
 * \param type: the error type
 * \param message: the string to display. Format specifiers are those
 * of printf()
 * \param args: additional arguments depending on the format string
 * \param prgm: non-zero means the error has been generated by the program
 * (not a source file error) and is passed as an argument to (*onfatal)()
 *//*=========================================================================*/
void verr(errtype_t type, const char* message, va_list args, int prgm)
{
    const char* s;

    last_line = eline;
    last_col = ecolumn;
    last_lvl = type;

    switch (type)
    {
        case F: s = ferrstr; ++error_count; is_fatal = 1; break;
        case E: s = errstr; ++error_count; break;
        case W: s = warnstr; ++warning_count; break;
        case N: s = notestr; break;
    }

    fprintf(stderr, "%s", s);
    vfprintf(stderr, message, args);
    fputc('\n', stderr);

    if (type == F && onfatal)
        (*onfatal)(prgm);
}

/**
 * \} Errors
 * \} Commons
 */
